---
rootDir: /home/nicolas/ACCOMP/
filenames:
  # cert_file: cert.csv
  # grades_file: grades.csv
  student_profile_file: profiles.csv
  # OUTPUT_yyyymmdd:
  #  aggrData_file: aggrData.csv
  #  allEvents_file: allEvents.csv # events_file
  #  allEvents_accountabilityFiltered_file: allEvents_accountabilityFiltered.csv # eventsTrack_file
  #  distinctEvents_perUser_file: distinctEvents_perUser.csv
  #  events_User_file: events_User.csv # events_perUser_file
  #  sessions_User_file: sessions_User.csv # sessions_perUser_file
  #  timeEvent_userDay_file: timeEvent_userDay.csv
courses:
- course_id: course-v1:UAMx+WebApp+1T2019a
  course_name: UAM WebApp 1T 2019A
mongo_connection:
  host: localhost # '150.244.59.136'
  port: 27017
  dbname: edxmongo_nico  # edxmongo
  # user: None # user
  # pwd: None # pwd
# https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# https://rollout.io/blog/yaml-tutorial-everything-you-need-get-started/
# https://www.tutorialspoint.com/yaml/index.htm
# https://en.wikipedia.org/wiki/YAML
...
